import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import NavbarGlobals from "@/modules/NavbarGlobal";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={poppins.className}>
        <Providers>
          <div className="h-full">{children}</div>
          <div className="w-full">
            <NavbarGlobals />
          </div>
        </Providers>
      </body>
    </html>
  );
}
