import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import NavbarGlobals from "@/modules/NavbarGlobal";
import Providers from "./providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={poppins.className}>
        <Providers>
          <div className="max-w-md mx-auto h-full">
            <div className="h-full ">{children}</div>
            <div className="w-full">
              <NavbarGlobals />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
